# Conexão com o PostgreSQL do Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/ordersystemdb
spring.datasource.username=jma_admin
spring.datasource.password=admin_password
spring.datasource.driverClassName=org.postgresql.Driver

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilitar DEBUG
logging.level.org.springframework.security=DEBUG